import { Component } from '@angular/core';

/** Placeholder text until counsel signs off the final terms. */
@Component({
  selector: 'app-terms',
  templateUrl: './legal-page.component.html',
  styleUrl: './legal-page.component.scss',
})
export class TermsComponent {
  protected readonly title = 'Terms of Use';
  protected readonly body = [
    'PrepAI is a study aid. Lessons are generated by AI and may contain mistakes, so check important answers against your textbook.',
    'Free accounts get a daily number of sessions. Paid plans are billed in Indian rupees through Razorpay.',
    'Do not share your account. You are responsible for activity on your account.',
  ];
}
